name: Merge Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  store-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Store Sync
        uses: jamiemccleave/shopify-multi-store-deployer@v1.0
        with:
          from_branch: "develop"
          to_branch: "devstores/storeone"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
